### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by pion-changho** [facebookresearch/MetaCLIP#25]
Location: Page 2, end of the Introduction section.

Issue: The text mentions "400 image-text pairs," but I believe it should be "400M" (400 million). Please confirm and correct if necessary.
<img width="1450" alt="스크린샷 2023-11-02 오후 4 02 06" src="https://github.com/facebookresearch/MetaCLIP/assets/135206226/b6fea01c-0481-4fdd-a083-ec71a86e3148">

**Comment by howardhsu** [comment]
good catch, will revise for the next arxiv version.
