### ISSUE TITLE
Potential Feature Request: Adding checkpoints to `pretrain.py`

### ISSUE THREAD

**Issue by Andy-LZH** [facebookresearch/MetaCLIP#26]
Congrats on getting this insightful paper out, and I will definitely use it as a backbone in my research, really nice work. 

However I do have one minor feedback on how to load MetaCLIP checkpoints at this stage. Right now's process(hopefully I did not do something wrong) was a bit tedious, as I cannot strictly follow below line
```py
model, _, preprocess = open_clip.create_model_and_transforms('ViT-B-32-quickgelu', pretrained='metaclip/b32_400m.pt')
``` 
to download weights and load models. I'm wondering whether the team is considering to add few simple lines of code to include the model checkpoints for a little bit better user experience.  Thanks.

**Comment by howardhsu** [comment]
thx, it's in our TODO list to download online w/o artificial local path. We are limit on man power so feel free to PR a solution if you have one.

**Comment by Andy-LZH** [comment]
@howardhsu Thanks for the reply and very happy to help, it's an exciting project and do let me know what I could do to also bring item down from TODO list.
