### ISSUE TITLE
Clarification: Does MetaCLIP actually use the updated training method as described in the paper?

### ISSUE THREAD

**Issue by shelbywhite** [facebookresearch/MetaCLIP#46]
Does MetaCLIP _actually_ use the updated training method as described in the paper?

According to the readme of this repo it says: "All MetaCLIP adhere to OpenAI CLIP training setup" which implies that MetaCLIP models shown in this repo don't actually leverage the new technique MetaCLIP uses for training the models itself. I hope this is not the case, but would be helpful to clarify what this statement means.

**Comment by howardhsu** [comment]
what do you mean by "updated training method"? we didn't invent/introduce any "new technique" but follow OpenAI training recipe closely to avoid confounding factors on optimization/lr etc. that was used by other open source CLIP models than comparing to OpenAI CLIPs.
