### ISSUE TITLE
How to implement English Language IDentification (LID)？

### ISSUE THREAD

**Issue by hbchen121** [facebookresearch/MetaCLIP#48]
How do you implement the function o "English Language IDentification (LID)" in the paper? 

Thanks~ Looking forward to your reply

**Comment by howardhsu** [comment]
In the paper we use a production LID model. In this open-source version you can try FastText: https://github.com/facebookresearch/MetaCLIP/blob/43ba9bc254e6eafe03f9dd7fbc79319484b070a6/metaclip/cc_matching.py#L24
